# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# ======================================================== #
# Determines when the action is triggered                  #
# ======================================================== #

on: [push, pull_request]
name: linter

# ======================================================== #
# Determine actions to take                                #
# ======================================================== #

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
        - name: Checking out the repository
          uses: actions/checkout@v3

        - name: Setting up R
          uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true

        - name: Installing dependencies
          uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: lintr

        - name: Picking on the coding style
          run: |
            library(lintr)
            excluded_code <- list(
              "R/FleissEveritt_test_paired_cxc.R" = 18,
              "R/JonckheereTerpstra_test_rxc.R" = 57,
              "R/JonckheereTerpstra_test_rxc.R" = 60,
              "R/RBG_test_and_CI_stratified_2x2.R" = 32,
              "R/RBG_test_and_CI_stratified_2x2.R" = 33,
              "R/the_1xc_table_tests.R" = 41,
              "R/the_1xc_table_tests.R" = 47,
              "R/the_2xc_table.R" = 52,
              "R/the_2xc_table.R" = 61,
              "R/the_2xc_table.R" = 93
            )
            style_rules <- list(
              T_and_F_symbol_linter(), assignment_linter(), brace_linter(),
              commas_linter(), commented_code_linter(), todo_comment_linter(),
              equals_na_linter(),
              function_left_parentheses_linter(), infix_spaces_linter(),
              no_tab_linter(), object_usage_linter(),
              absolute_path_linter(),
              pipe_continuation_linter(),
              semicolon_linter(), seq_linter(), single_quotes_linter(),
              spaces_inside_linter(), trailing_blank_lines_linter(),
              trailing_whitespace_linter(), undesirable_function_linter(),
              undesirable_operator_linter(), unneeded_concatenation_linter()
            )
            lint_package(linters = style_rules, exclusions = excluded_code)
          shell: Rscript {0}
